#!/bin/bash
# This script is a wrapper for omxplayer and bluez alsa devices on Raspberry Pi 3 with Stretch.
# This script really isn't necessary but for testing and debugging
# while building https://github.com/drumfreak/homebridge-bluetooth-soundbutton, I was running into
# issues with launching child-process with spawn escaping command line arguments
# like "-o alsa:foo" and so this workaround was created and I decided to share it.


# To execute from command line, after chmod +x bluetooth-play such as:
# ./bluetooth-play /usr/bin/omxplayer.bin default /home/pi/sounds/mySound.mp3
# ./<name of script> <full path to player> <alsa PCM name> <sound file full path>


# Note: DO NOT use the default "/usr/bin/omxplayer" but instead the full path to the omxplayer.bin file.
#       /usr/bin/omxplayer.bin  
#	*** NOT /usr/bin/omxplayer
#      The non .bin file is a wrapper and does not return the child PID so it will not terminate when turning
#      off the switch in homebridge.

exit_script() {
    echo ""
    echo "I was asked to die, so I shall. Goodbye world!"
    echo "Stopping: $player for Speaker: $speaker playing file $playFile"
    echo "Sending DEATH to the child pid: $pid"
    echo "Cleaning up child: $pid"
    trap - SIGHUP SIGINT SIGTERM # clear the trap
    kill -9 $pid # Sends DEATH to the child/sub processes
    echo ""
    echo ""
}

trap exit_script SIGHUP SIGINT SIGTERM

if [ "$1" == "" ]; then
	echo "Error:"
	echo "    Missing player, launch with bluetooth-play <playerExec> <soundDevice> <inputFile>"
	echo "    Example: ./bluetooth-play /usr/bin/omxplayer.bin default /home/pi/sounds/mySound.mp3"
	echo ""
	echo ""
	exit;
fi


if [ "$2" == "" ]; then
	echo "Error:"
	echo "    Missing adapter, launch with bluetooth-play <playerExec> <soundDevice> <inputFile>"
	echo "    Example: ./bluetooth-play /usr/bin/omxplayer.bin default /home/pi/sounds/mySound.mp3"
	echo ""
	echo ""
	exit;
fi


if [ "$3" == "" ]; then
	echo "Error:"
	echo "    Missing input file, launch with bluetooth-play <playerExec> <alsaDevice> <inputFile>"
	echo "    Example: ./bluetooth-play /usr/bin/omxplayer.bin default /home/pi/sounds/mySound.mp3"
	echo ""
	echo ""
	exit;
fi

player=$1
speaker="-o alsa:$2"
playFile=$3

echo "launching $player $speaker $playFile" 

$player $speaker $playFile &

pid=$!

echo "The Child PID has been born as: $pid"

wait $pid

