#!/bin/bash
# This script is for reconnecting to bluetooth devices that have been trusted and by the addresses below.
# run as: /home/pi/btrestart  (for soft reconnect)
# run as: /home/pi/btrestart hard   (for service restart and hard reconnect)

# This is intended to actually reconnect bluetooth devices and wait for the Service to be registered so you 
# can play audio through them. Typically, the examples on the net call for:
# bluetoothctl <<< EOF 
#   some commands here
# EOF

# However, that method does not wait for the connection, so we will use coproc and wait for proper responses.
# In my example below, 3 devices will be reconnected if their bluetooth is ON.  Replace XX:XX:XX:XX:XX:XX for your actual
# device hardware address / ID in bluetoothctl
# Enjoy!
# https://github.com/drumfreak

if [ "$1" == "hard" ]; then
	sudo cp /etc/asound.conf /usr/share/alsa/alsa.conf.d/30-asound.conf
	wait $!

	echo "/etc/asound.conf copied to /usr/share/alsa/alsa.conf.d/30-asound.conf"
	echo "Gracefully disconnecting from bluetooth devices"

	echo "restarting bluetooth services"
	sudo systemctl restart bluetooth
	wait
	sleep 3
	
	sudo systemctl status bluetooth
	wait
	sleep 3

	echo "restarting dbus-org.bluez service"
	sudo systemctl  restart dbus-org.bluez
	wait
	sleep 3

	sudo systemctl status dbus-org.bluez
	wait
fi

echo ""
echo ""
echo "reconnecting to bluetooth devices"

echo "starting bluetoothctl"
coproc bluetoothctl -a

cmd() {
  echo "> $*"
  echo "$@" >&${COPROC[1]}
}

NOTHING=__N0L1NE__
getLine() { local a; read -t 1 -ru ${COPROC[0]} a; (( $? > 127 )) && echo $NOTHING || echo "$a"; }

waitFor() {
  local line="" cond="$*"
  echo "waiting for $cond"
  while line=$(getLine); ! grep -qE "$cond" <<<"$line"; do
    [ "$line" != $NOTHING ] && echo "btctl> $line" >&2
  done
  echo "$line"
}

waitFor "Agent registered"

# disconnect and reconnect bt device by ID
cmd disconnect XX:XX:XX:XX:XX:XX
waitFor "Successful disconnected|Failed"

cmd connect XX:XX:XX:XX:XX:XX
waitFor "ServicesResolved|Failed"

# disconnect and reconnect bt device by ID
cmd disconnect XX:XX:XX:XX:XX:XX
waitFor "Successful disconnected|Failed"

cmd connect XX:XX:XX:XX:XX:XX
waitFor "ServicesResolved|Failed"

# disconnect and reconnect bt device by ID
cmd disconnect XX:XX:XX:XX:XX:XX
waitFor "Successful disconnected|Failed"

cmd connect XX:XX:XX:XX:XX:XX
waitFor "ServicesResolved|Failed"

cmd quit
wait

echo "busctl tree org.bluez output:"

busctl tree org.bluez
