#!/bin/bash

if ["$1" == "hard"]; then

	sudo cp /etc/asound.conf /usr/share/alsa/alsa.conf.d/30-asound.conf
	wait $!

	echo "/etc/asound.conf copied to /usr/share/alsa/alsa.conf.d/30-asound.conf"

	echo "Gracefully disconnecting from bluetooth devices"

	echo "restarting bluetooth services"
	sudo systemctl restart bluetooth
	wait $!

	sudo systemctl status bluetooth
	wait $!

	sleep 3

	echo "restarting dbus-org.bluez service"
	sudo systemctl  restart dbus-org.bluez
	wait $!

	sudo systemctl status dbus-org.bluez
	wait $!
fi

echo ""
echo ""


echo "reconnecting to bluetooth devices"

#bluetoothctl -a << EOF
#agent on
#EOF
echo "starting bluetoothctl"
coproc bluetoothctl -a

cmd() {
  echo "> $*"
  echo "$@" >&${COPROC[1]}
}

NOTHING=__N0L1NE__

getLine() { local a; read -t 1 -ru ${COPROC[0]} a; (( $? > 127 )) && echo $NOTHING || echo "$a"; }

waitFor() {
  local line="" cond="$*"
  echo "waiting for $cond"
  while line=$(getLine); ! grep -qE "$cond" <<<"$line"; do
    [ "$line" != $NOTHING ] && echo "btctl> $line" >&2
  done
  echo "$line"
}

waitFor "Agent registered"

cmd disconnect 10:B7:F6:25:86:2C

waitFor "Successful disconnected|Failed"

cmd connect 10:B7:F6:25:86:2C
waitFor "ServicesResolved|Failed"


cmd disconnect FC:A1:83:0F:3B:93
waitFor "Successful disconnected|Failed"

cmd connect FC:A1:83:0F:3B:93
waitFor "ServicesResolved|Failed"

cmd disconnect FC:A1:83:60:A7:14
waitFor "Successful disconnected|Failed"

cmd connect FC:A1:83:60:A7:14
waitFor "ServicesResolved|Failed"

cmd quit
wait

#connect FC:A1:83:0F:3B:93
#connect FC:A1:83:60:A7:14


echo "busctl tree org.bluez:"


busctl tree org.bluez
